"""Add research_context to learning_paths

Revision ID: bd8e7738cbe4
Revises: 696eee02c3dd
Create Date: 2026-01-30 12:13:11.713025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8e7738cbe4'
down_revision: Union[str, Sequence[str], None] = '696eee02c3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'challenge_attempts', 'users', ['user_id'], ['id'])
    op.add_column('learning_paths', sa.Column('research_context', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'learning_paths', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'node_progress', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'node_progress', type_='foreignkey')
    op.drop_constraint(None, 'learning_paths', type_='foreignkey')
    op.drop_column('learning_paths', 'research_context')
    op.drop_constraint(None, 'challenge_attempts', type_='foreignkey')
    # ### end Alembic commands ###
