# agents/research_agent.py

from typing import Dict, Any, Optional
import json

from services.llm_client import call_gemini, google_web_search, web_fetch
from services.opik_client import create_opik_tracer
from services.ab_testing import select_variant

# -----------------------------------------------------------------------------
# System Prompt
# -----------------------------------------------------------------------------

RESEARCH_SYSTEM_PROMPT = """
You are an expert curriculum designer and career coach.

Given a user's goal (any domain: career, fitness, creative, etc.) and provided research content, you will:
1. Synthesize the main competencies and subskills required to achieve that goal *based on the provided research*.
2. Express them as structured JSON.
3. Use specific, concrete language; avoid vague phrasing.
4. Ensure the competencies are grounded in the provided external content.

Quality requirements (very important):
- Each competency should be specific enough to guide learning (avoid overly broad items like "LLM Basics").
- The description must include: why it matters, 2–3 key subskills, and a concrete outcome.
- Example tasks must be realistic and job-like (debugging, designing, shipping, optimizing), not textbook.
- Include "tacit" or "hidden" expertise when evident (e.g., tradeoffs, operational pitfalls).
- Prefer 10–20 competencies with strong coverage over many shallow ones.

Output strictly valid JSON in this schema:
{
  "normalized_goal": "...",
  "competencies": [
    {
      "id": "c1",
      "name": "Short name of competency",
      "description": "3-5 sentence explanation with why it matters, key subskills, and outcome",
      "type": "technical | conceptual | soft-skill | meta",
      "example_tasks": [
        "Example real-world task #1",
        "Example real-world task #2"
      ]
    }
  ]
}
"""

# Bump this when the prompt changes meaningfully.
PROMPT_VERSION = "research_v1"
EXPERIMENT_NAME = "research_prompt"
EXPERIMENT_VARIANTS = ["A", "B"]

# -----------------------------------------------------------------------------
# Opik Tracer (module-level singleton)
# -----------------------------------------------------------------------------

opik_tracer = create_opik_tracer(
    name="research-agent",
    project_name="learning-paths",
    tags=["research", "competency-extraction"],
    metadata={
        "component": "research_agent",
    },
)

# -----------------------------------------------------------------------------
# Agent Execution
# -----------------------------------------------------------------------------

EVAL_SYSTEM_PROMPT = """
You are a meticulous and impartial curriculum evaluator.

Your task is to assess the quality of a list of competencies generated by another AI agent for a given user goal.

You will be given the user's goal and the generated competencies in JSON format.

Your evaluation must be based on the following criteria:
1.  **Relevance:** How relevant are the competencies to the stated goal? (e.g., Do they directly contribute to achieving the goal?)
2.  **Completeness:** Does the list cover the most critical areas needed to achieve the goal? Are there any obvious gaps?
3.  **Clarity & Actionability:** Are the competency names and descriptions clear? Are the example tasks concrete and actionable?

You must provide a score for each dimension (0-5) and a final overall score (a float between 0.0 and 1.0).

Output STRICT JSON:
{
  "dimension_scores": [
    { "name": "Relevance", "score": 0-5, "comment": "Your reasoning for the score." },
    { "name": "Completeness", "score": 0-5, "comment": "Your reasoning for the score." },
    { "name": "Clarity & Actionability", "score": 0-5, "comment": "Your reasoning for the score." }
  ],
  "overall_score": 0.0,
  "summary": "A brief summary of your evaluation."
}
"""

def eval_research_quality(goal_title: str, competencies_json: Dict[str, Any]):
    """
    Uses an LLM-as-judge to evaluate the quality of the generated competencies.
    """
    eval_user_msg = f"""
    User Goal: {goal_title}

    Generated Competencies JSON:
    {json.dumps(competencies_json, indent=2)}

    Please evaluate the quality of this output based on the criteria provided.
    """
    
    try:
        raw_output = call_gemini(
            system_instruction=EVAL_SYSTEM_PROMPT,
            user_message=eval_user_msg,
        )
        parsed_eval = json.loads(raw_output)
        return parsed_eval.get("overall_score", 0.0), parsed_eval
    except Exception:
        # In case of any failure (model call, JSON parse), return a neutral score
        return 0.5, {"error": "Evaluation failed"}


def run_research_agent(
    user_id: str,
    goal_title: str,
    goal_description: Optional[str],
    domain_hint: Optional[str],
    level: Optional[str],
) -> Dict[str, Any]:
    """
    Derives competencies for a user goal using web research.
    Fully instrumented with Opik.
    """
    from opik import start_as_current_trace, start_as_current_span

    variant = select_variant(user_id, EXPERIMENT_NAME, EXPERIMENT_VARIANTS)
    prompt_by_variant = {
        "A": RESEARCH_SYSTEM_PROMPT,
        "B": RESEARCH_SYSTEM_PROMPT,
    }
    system_prompt = prompt_by_variant[variant]

    with start_as_current_trace(
        name="derive_competencies",
        tags=["research", "competency-extraction", PROMPT_VERSION, f"{EXPERIMENT_NAME}:{variant}"],
        metadata={
            "user_id": user_id,
            "goal_title": goal_title,
            "domain_hint": domain_hint,
            "level": level,
            "prompt_version": PROMPT_VERSION,
            "experiment": EXPERIMENT_NAME,
            "variant": variant,
        },
        project_name="learning-paths"
    ) as trace:
        search_queries = [
            f"{goal_title} job description requirements",
            f"{goal_title} expert blogs best practices",
            f"{goal_title} github projects examples",
        ]

        # Perform web searches
        search_results = []
        for query in search_queries:
            results = google_web_search(query)
            search_results.extend(results.get("organic_results", results.get("results", [])))

        # Filter and get top URLs
        urls_to_fetch = []
        for res in search_results:
            if res.get("link") and res.get("link") not in urls_to_fetch:
                urls_to_fetch.append(res["link"])
            if len(urls_to_fetch) >= 5:  # Limit to top 5 URLs for content fetching
                break

        # Fetch content from URLs
        fetched_content = []
        if urls_to_fetch:
            for url in urls_to_fetch:
                try:
                    content = web_fetch(url)
                    fetched_content.append({"url": url, "content": content})
                except Exception as fetch_exc:
                    continue

        user_msg = f"""
User goal title: {goal_title}
Goal description: {goal_description or "N/A"}
Domain hint: {domain_hint or "N/A"}
Level: {level or "N/A"}

---
Research Content:
"""
        if fetched_content:
            for item in fetched_content:
                user_msg += f"\nURL: {item['url']}\nContent:\n{item['content']}\n"
        else:
            user_msg += "\nNo external research content found. Relying on general knowledge."

        user_msg += """
---

Derive competencies as described, primarily using the provided Research Content.
"""

        def _parse_research(raw_text: str) -> Dict[str, Any]:
            cleaned = raw_text.strip()
            if cleaned.startswith("```"):
                lines = cleaned.splitlines()
                if len(lines) >= 3 and lines[-1].strip().startswith("```"):
                    cleaned = "\n".join(lines[1:-1]).strip()
            # Best-effort JSON extraction if extra text is present
            if "{" in cleaned and "}" in cleaned:
                cleaned = cleaned[cleaned.find("{") : cleaned.rfind("}") + 1]
            return json.loads(cleaned)

        raw_output = ""
        parsed = None
        for attempt in range(2):
            with start_as_current_span(
                name="call_gemini",
                type="llm",
                metadata={"model": "gemini", "attempt": attempt + 1}
            ) as span:
                raw_output = call_gemini(
                    system_instruction=system_prompt,
                    user_message=user_msg,
                )
                span.input = {"user_msg": user_msg[:500]}  # Limit input size
                span.output = {"raw_output": raw_output[:500]}  # Limit output size

            try:
                parsed = _parse_research(raw_output)
                break
            except Exception:
                print("RESEARCH_AGENT_JSON_PARSE_ERROR")
                print(raw_output[:2000])
                parsed = {
                    "normalized_goal": goal_title,
                    "competencies": [],
                    "error": "invalid_json_from_model",
                }

        if parsed is None:
            parsed = {
                "normalized_goal": goal_title,
                "competencies": [],
                "error": "invalid_json_from_model",
            }

        # Fallback: ensure we always return a minimum competency list
        if not parsed.get("competencies"):
            parsed = {
                "normalized_goal": goal_title,
                "competencies": [
                    {
                        "id": "c1",
                        "name": "Foundational knowledge for the goal",
                        "description": "Build the core concepts and vocabulary needed to start working in this domain. Focus on the basic tools, terminology, and mental models so later skills have a stable base.",
                        "type": "conceptual",
                        "example_tasks": [
                            "Summarize the most important concepts and terminology for the goal.",
                            "Explain how a beginner would approach a simple task in this domain."
                        ],
                    }
                ],
                "error": parsed.get("error"),
            }

        # ---- Evaluation hook --------------------------------------------------
        score, details = eval_research_quality(goal_title, parsed)

        trace.input = {"goal_title": goal_title, "goal_description": goal_description}
        trace.output = {
            "competencies_count": len(parsed.get("competencies", [])),
            "search_queries_count": len(search_queries),
            "urls_fetched": len(fetched_content),
            "has_research_context": bool(fetched_content),
            "llm_invalid_json": parsed.get("error") == "invalid_json_from_model",
            "eval_overall_score": score,
            "eval_dimension_scores": details.get("dimension_scores"),
            "eval_failed": "error" in details,
            "used_fallback_competencies": len(parsed.get("competencies", [])) == 1 and parsed.get("competencies", [])[0].get("id") == "c1",
        }

        return {"competencies": parsed, "research_context": fetched_content}
